{% set version = "2.3.2" %}
{% set sha256 = "ee0c74852c102140fc590541950127b63a3c6fa4592305c16738d23ed65f8ac3" %}

package:
  name: libgd
  version: {{ version }}

source:
  url: https://github.com/libgd/libgd/releases/download/gd-{{version}}/libgd-{{ version }}.tar.gz
  sha256: {{ sha256 }}
  patches:
    # see: https://github.com/libgd/libgd/issues/367
    - patches/linux-fontconfig-basic.patch

build:
  skip: True  # [win]
  number: 3
  run_exports:
    # https://abi-laboratory.pro/?view=timeline&l=libgd
    - {{ pin_subpackage('libgd', max_pin='x.x') }}
  # 5/19/2021: When packaging libgd the error was for icu and expat "run-exports library package 
  # in requirements/run but it is not used" 
  ignore_run_exports:
    - icu
    - expat

requirements:
  build:
    - {{ compiler('c') }}
    - automake
    - libtool
    - gettext
    - pkg-config
    - make
  host:
    - expat
    - fontconfig
    - freetype
    - icu
    - jpeg
    - libiconv  # [osx]
    - libpng
    - libtiff
    - libwebp
    - zlib
  run:
    - expat
    - fontconfig
    - freetype
    - icu
    - jpeg
    - libiconv  # [osx]
    - libpng
    - libtiff
    - libwebp
    - zlib

test:
  commands:
    - test -f $PREFIX/lib/libgd.a  # [linux]
    - test -f $PREFIX/lib/libgd${SHLIB_EXT}  # [not win]

about:
    home: http://libgd.github.io/
    summary: 'Library for the dynamic creation of images.'
    license: GD
    license_family: BSD
    license_file: COPYING
    dev_url: https://github.com/libgd/libgd

extra:
  recipe-maintainers:
    - croth1
    - ChrisBarker-NOAA
    - ocefpaf
