{% set version = "2.2.5" %}
{% set sha256 = "a66111c9b4a04e818e9e2a37d7ae8d4aae0939a100a36b0ffb52c706a09074b5" %}

package:
  name: libgd
  version: {{ version }}

source:
  fn: libgd-{{ version }}.tar.gz
  url: https://github.com/libgd/libgd/releases/download/gd-{{version}}/libgd-{{ version }}.tar.gz
  sha256: {{ sha256 }}
  patches:
    # see: https://github.com/libgd/libgd/issues/367
    - patches/linux-fontconfig-basic.patch

build:
  skip: True  # [win]
  number: 0

requirements:
  build:
    - pkg-config
    - gettext
    - zlib 1.2.8
    - freetype 2.7
    - jpeg 9*
    - libpng >=1.6.28,<1.7
    - libtiff >=4.0.3,<4.0.8
    - fontconfig 2.12.*
    - libiconv
    - icu 58.*
    - expat
    - libwebp 0.5.*
    - automake
  run:
    - zlib 1.2.8
    - freetype 2.7
    - jpeg 9*
    - libpng >=1.6.28,<1.7
    - libtiff >=4.0.3,<4.0.8
    - fontconfig 2.12.*
    - libiconv
    - icu 58.*
    - expat
    - libwebp 0.5.*

test:
  commands:
    - test -f $PREFIX/lib/libgd.a      # [linux]
    - test -f $PREFIX/lib/libgd.dylib  # [osx]
    - test -f $PREFIX/lib/libgd.la
    - conda inspect linkages -p $PREFIX libgd  # [not win]
    - conda inspect objects -p $PREFIX libgd  # [osx]

about:
    home: http://libgd.github.io/
    summary: 'Library for the dynamic creation of images.'
    license: GD
    license_family: BSD
    license_file: COPYING

extra:
  recipe-maintainers:
    - croth1
    - ChrisBarker-NOAA
    - ocefpaf
