{% set version = "2.3.1" %}
{% set sha256 = "e904a35fd3379ddb2d7c64f929b7cbdf0422863646dae252be0029b9e47c9fe3" %}

package:
  name: libgd
  version: {{ version }}

source:
  url: https://github.com/libgd/libgd/releases/download/gd-{{version}}/libgd-{{ version }}.tar.gz
  sha256: {{ sha256 }}
  patches:
    # see: https://github.com/libgd/libgd/issues/367
    - patches/linux-fontconfig-basic.patch

build:
  skip: True  # [win]
  number: 3
  run_exports:
    # https://abi-laboratory.pro/?view=timeline&l=libgd
    - {{ pin_subpackage('libgd', max_pin='x.x') }}

requirements:
  build:
    - {{ compiler('c') }}
    - automake
    - libtool
    - gettext
    - pkg-config
    - make
  host:
    - expat
    - fontconfig
    - freetype
    - icu
    - jpeg
    - libiconv  # [osx]
    - libpng
    - libtiff
    - libwebp
    - zlib
  run:
    - expat
    - fontconfig
    - freetype
    - icu
    - jpeg
    - libiconv  # [osx]
    - libpng
    - libtiff
    - libwebp
    - zlib

test:
  commands:
    - test -f $PREFIX/lib/libgd.a  # [linux]
    - test -f $PREFIX/lib/libgd${SHLIB_EXT}  # [not win]

about:
    home: http://libgd.github.io/
    summary: 'Library for the dynamic creation of images.'
    license: GD
    license_family: BSD
    license_file: COPYING

extra:
  recipe-maintainers:
    - croth1
    - ChrisBarker-NOAA
    - ocefpaf
