{% set version = "2.2.2" %}

package:
  name: libgd
  version: {{ version }}

source:
  fn: libgd-{{ version }}.tar.gz
  url: https://github.com/libgd/libgd/releases/download/gd-{{version}}/libgd-{{ version }}.tar.gz
  sha256: 9890fd86792883df9201b2d87e7b68865a5e893f75132758c1e5c240a0462dc6
  patches:
    - osx_version.patch

build:
  skip: true  # [win]
  number: 0

requirements:
  build:
    - pkg-config
    - automake
    - gettext
    - zlib 1.2.*
    - freetype 2.6.*
    - jpeg 9*
    - libpng >=1.6.21,<1.7
    - libtiff 4.0.*
    - fontconfig 2.11.*
    - libiconv
    - expat
  run:
    - zlib 1.2.*
    - freetype 2.6.*
    - jpeg 9*
    - libpng >=1.6.21,<1.7
    - libtiff 4.0.*
    - fontconfig 2.11.*
    - libiconv
    - expat

test:
  commands:
    - test -f $PREFIX/lib/libgd.a      # [linux]
    - test -f $PREFIX/lib/libgd.dylib  # [osx]
    - test -f $PREFIX/lib/libgd.la
about:
    home: http://libgd.github.io/
    summary: library for the dynamic creation of images
    license: GD license
    license_family: Other
    license_file: COPYING

extra:
    recipe-maintainers:
      - croth1
