travis:
  secure:
    BINSTAR_TOKEN: wKotsf7fJ07vIYK4MoP6hED8ragt9fhFP8Bcirq2Gp5byozBk6i+XHc/9V8dBx4okOXSNS6DaR/kLRCTiB/7yMx71nekdqIlxwPpdevCwyG9rLxxW2XctaJUgp+Oa89+gmEo/I9yE7uy0K4r7mtQDo5IQvNc75TO7JziJup0erpnhZmWyKAToO9foMIJ1UULYZ+URLfUsJ7PewoCIyojXkWPYVIAqDAdaMlVWpSRV9Sf95Xk/AlNAondwjEcrjMxalA0yvIoCz2W0aHTG0jCZU+j+5qKsZ3Z0KgR1GJ8vL+e83V9iR+Lh14Jiaui/viRaEWJqM+5/YDicnJIkLrcHOIU4paY84kgl/Yzvzl/4RCCQpJNCSb6e6BzbcU2Y+IN0r7wEDb6/4UGgNORdYmQHpvMfvCYZHeQdfXPQstuc1OwioiNppbT/WPxUHJWOKi2h+quO3Ke0PDNW0urhX9F56kzq209GDcM/vep0L0JOoCJiFxbuUNecuQ+qJQIEY6+cu/KvuOWdINToHBpcwkm5bR88+lz2ENWEVS8GnsZv5sBsCTB5oXHNjU/8MDMGYIemvVfPZ2CkcZgeEsZsPf1d8torpiTMvzzgOYMQvcepwHqiPb9C/PtCv6ogHjPSQGC8SSCSnuPGjPAjYUmB1VrI4iMUxH9YCXcuSlxAwjgwdw=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
